In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3])

In [9]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
mylist


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
mymatrix=np.array(mylist)

In [13]:
mymatrix.shape

(3, 3)

In [14]:
mynewmatrix = np.array(mylist)

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [25]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [31]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.random.rand(5,5)

array([[0.2309411 , 0.97654076, 0.33409781, 0.85135378, 0.83563404],
       [0.04188245, 0.91889134, 0.72159549, 0.30079333, 0.51586605],
       [0.64823147, 0.44090637, 0.78648472, 0.73767522, 0.75875803],
       [0.42228607, 0.66009918, 0.26368443, 0.90220987, 0.03971047],
       [0.38642234, 0.22069861, 0.1341905 , 0.04360942, 0.46486655]])

In [38]:
np.random.randn(10)

array([ 1.63090369, -0.80532832,  0.83592487, -0.08654194,  0.54327196,
        0.75226011, -0.96801998,  0.86205604, -0.06991909,  0.5979864 ])

In [41]:
np.random.randint(1,100,10)

array([29, 60, 79, 21, 82,  8, 74,  6, 63, 83])

In [52]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [53]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [56]:
arr = np.arange(25)

In [58]:
ranarr = np.random.randint(0,50,10)

In [59]:
ranarr

array([28,  0, 46,  5, 12, 29, 40, 49, 19, 47])

In [60]:
arr.shape

(25,)

In [61]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
ranarr.max()

49

In [64]:
ranarr

array([28,  0, 46,  5, 12, 29, 40, 49, 19, 47])

In [65]:
ranarr.min()

0

In [66]:
ranarr.argmax()

7

In [67]:
ranarr.argmin()

1

In [68]:
ranarr.dtype

dtype('int32')